[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Freddy Krueger for lethal Company"
websiteUrl = "https://github.com/FelixAllard/FreddyKrueger-LC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.14.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/ExampleEnemy.dll"
target = "plugins/ExampleEnemy/"

[[build.copy]]
source = "../../FreddyKrueger/AssetBundles/StandaloneWindows/modassets"
target = "plugins/ExampleEnemy/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]