[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Freddy Krueger joins Lethal Company as a brand new monster"
websiteUrl = "https://github.com/FelixAllard/FreddyKrueger-LC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.14.2"
Sigurd-CSync = "3.1.1"
Evaisa-HookGenPatcher = "0.0.5"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/FreddyKrueger.dll"
target = "plugins/FreddyKrueger/"

[[build.copy]]
source = "../../UnityProject/AssetBundles/StandaloneWindows/freddymodassets"
target = "plugins/FreddyKrueger/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "monsters", "mods", "bepinex" ]