[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Freddy Krueger joins Lethal Company as a brand new monster. Early Access"
websiteUrl = "https://github.com/FelixAllard/FreddyKrueger-LC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.14.2"
xilophor-LethalNetworkAPI = "2.1.6"
Lordfirespeed-OdinSerializer = "2022.11.9"
Sigurd-CSync = "3.1.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/FreddyKrueger.dll"
target = "plugins/FreddyKrueger/"

[[build.copy]]
source = "../../FreddyKrueger/AssetBundles/StandaloneWindows/freddymodassets"
target = "plugins/FreddyKrueger/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
{"name":"Monsters","slug":"monsters"}
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]